# Generated by Django 4.0.4 on 2022-04-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название принтера')),
                ('api_key', models.CharField(max_length=32, verbose_name='ключ доступа к API')),
                ('check_type', models.CharField(choices=[('K', 'кухня'), ('C', 'клиент')], max_length=1, verbose_name='тип чека которые печатает принтер')),
                ('point_id', models.CharField(max_length=50, verbose_name='точка к которой привязан принтер')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('K', 'kitchen'), ('C', 'CLIENT')], max_length=1, verbose_name='тип чека')),
                ('order', models.JSONField(verbose_name='информация о заказе')),
                ('status', models.CharField(choices=[('N', 'новый'), ('R', 'отображённый'), ('P', 'напечатанный')], max_length=1, verbose_name='статус чека')),
                ('pdf_file', models.FileField(upload_to='', verbose_name='ссылка на созданный PDF-файл')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.printer', verbose_name='принтер')),
            ],
        ),
    ]
